-- Fix column lengths to accommodate ANAC data (minimal schema)

ALTER TABLE cig ALTER COLUMN cig TYPE VARCHAR(50);
ALTER TABLE cig ALTER COLUMN oggetto_gara TYPE VARCHAR(4000);
ALTER TABLE cig ALTER COLUMN oggetto_principale_contratto TYPE VARCHAR(500);
ALTER TABLE cig ALTER COLUMN stato TYPE VARCHAR(100);
ALTER TABLE cig ALTER COLUMN provincia TYPE VARCHAR(100);
ALTER TABLE cig ALTER COLUMN sezione_regionale TYPE VARCHAR(100);
ALTER TABLE cig ALTER COLUMN descrizione_cpv TYPE VARCHAR(1000);
ALTER TABLE cig ALTER COLUMN esito TYPE VARCHAR(100);
